version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-210-255-177.compute-1.amazonaws.com
            database: dal9r3bef0rar7
            user: jkdejbvvuhhclp
            password: 4142d9e0cb3bec65620ceb69ca0b69e2666cb76fdd45a046b82e7188c63d8f1d
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
